api:
  binance_api_key: ""
  binance_api_secret: ""
  database_url: sqlite:///valvulin.db

risk:
  max_position_size_pct: 2.0
  max_daily_loss_pct: 3.0
  leverage: 1.0

data:
  cache_dir: data/cache
  export_dir: data/exports

backtester:
  initial_equity: 10000
  risk_per_trade_pct: 1.0
  commission_pct: 0.075
  maker_commission_pct: 0.05
  taker_commission_pct: 0.075
  max_daily_loss_pct: 4.0
  max_consecutive_losses: 4
  use_trailing_stop: true
  trailing_method: atr
  trailing_activation_r: 1.0
  trailing_atr_multiplier: 1.5
  default_stop_atr_multiplier: 1.0
  atr_period: 14
  volatility_atr_threshold: 5.0
  min_volume_ratio: 0.5
  use_session_limits: true
  trading_hours:
    start: "08:00"
    end: "20:00"
  export_directory: data/exports
  strategies:
    pullback: true
    breakout: true
    divergences: false
